cmd/main/main.go, go.mod, go.sum, pkg/usage/usage.go
Because
- upgrade usage collection
This commit
- move usage related code into the usage package
- trigger the reporter before shutting down the server
=> refactor: update usage reporter

integration-test/rest-destination-connector.js, integration-test/rest.js
Because
- integration test failed from 2nd running because created connectors is not cleaned
This commit
- add delete connectors after each test case and all created connectors in the teardown function
=> fix: add delete connectors when finishing testing

cmd/main/main.go, pkg/usage/usage.go
Because
- usage service could be not available and the mgmt server should be resilient with this situation.
This commit
- check the connection to the usage service then report only have a connection
=> chore: resilient with non-running usage service

cmd/init/db.go, integration-test/const.js
Because
-  update integration test when running with API gateway
This commit
- change the port to API gateway when running HOSTNAME=api-gateway
- update the init database by using FirstOrCreate when creating definitions in the database. If not doing so, `connector-backend-init` would fail when the database is being created already, making `connector-backend` unable to start.
=> chore: update integration test

.pre-commit-config.yaml, config/config.yaml
Because
- CORS configuration is set in docker-compose files
This commit
- remove cors default config
- upgrade pre-commit hooks
=> chore: change config and usage metric

.github/workflows/add-issue-to-prj.yml, .github/workflows/add-pr-to-prj.yml, README.md
Because
- instead of Visual Data Preparation, VDP is Versatile Data Pipeline now. We realise that as a general ETL infrastructure, VDP is capable of processing all kinds of unstructured data, and we should not limit its usage to only visual data. That's why we replace the word Visual with Versatile. Besides, the term Data Preparation is a bit misleading, users often think it has something to do with data labelling or cleaning. The term Data Pipeline is definitely more precise to capture the core concept of VDP.
This commit
- update to Versatile Data Pipeline
=> chore: update Visual Data Preparation to Versatile Data Pipeline

integration-test/const.js, integration-test/rest-destination-connector.js, integration-test/rest-source-connector.js
Because
- model backend uses a dummy model when running the integration test
This commit
-  update GitHub model tag in integration test
=> chore: update model instance name of dummy GitHub model

cmd/main/main.go, internal/external/external.go, pkg/usage/usage.go
Because
- backend service should not be terminated because of connection to other services
This commit
- replace fatal logs with error logs
=> fix: use error logs for usage

pkg/constant/constant.go
Because
- we use a more representative user ID
This commit
- update the default user id
=> refactor: update default user id

pkg/middleware/misc.go
Because
- we want to pass headers "owner-id" and "request-id" to the backend
This commit
- update custom header
=> refactor: update custom matcher

integration-test/grpc-destination-connector-private.js, integration-test/grpc-destination-connector-public.js, integration-test/grpc-source-connector-private.js, integration-test/grpc-source-connector-public.js, integration-test/helper.js, integration-test/rest-destination-connector-private.js, integration-test/rest-destination-connector-public.js, integration-test/rest-source-connector-private.js, integration-test/rest-source-connector-public.js, pkg/handler/publicHandler.go, pkg/service/service.go, pkg/service/utils.go
Because
- The user ID can be changed now (in Instill Cloud), so using the owner ID is not reliable
This commit
- refactor owner of a connector to use the UUID, not the ID
=> chore: change owner from using id to uuid

pkg/service/service.go, pkg/service/utils.go
Because
- We need to check jwt permission and also propagation it to other backend service
This commit
- support jwt-sub propagation
=> chore: support jwt-sub propagation

integration-test/grpc-destination-connector-public-with-jwt.js, integration-test/grpc-source-connector-public-with-jwt.js, integration-test/rest-destination-connector-public-with-jwt.js, integration-test/rest-source-connector-public-with-jwt.js, internal/resource/resource.go, pkg/handler/publicHandler.go
Because
- currently, if a user does not exist in mgmt-backend, returns 500 status error
This commit
- return 404 when a user does not exist
- return 401 when both `jwt-sub` and `owner-id` does not exist in the header 
- update tests
=> chore: return 404 for non-exist user and 401 for non-existent headers

cmd/main/main.go, cmd/worker/main.go, config/config.go, config/config.yaml, go.mod, go.sum, pkg/worker/check.go, pkg/worker/worker.go
Because
- for users who like to connect with Temporal Cloud directly, currently the only way is by mTLS auth
This commit
- enables Temporal client TLS configuration
=> chore: set up connector-backend mTLS connection for Temporal

config/config.go
Because
- the temopral config struct tags are missing
This commit
- add the corresponding tags
=> chore: fix missing config struct tags

.github/workflows/integration-test.yml, Makefile, integration-test/const.js, integration-test/grpc-destination-connector-public.js, integration-test/grpc.js, integration-test/rest-destination-connector-public.js, integration-test/rest.js
Because
- Need to simplify the integration test mode
This commit
- Add `API_GATEWAY_HOST`, `API_GATEWAY_PORT` and `API_GATEWAY_PROTOCOL` var. to simplify the integration test setting
- Adjust test timeout
=> chore: refactor integration test mode and update test timeout

pkg/handler/privateHandler.go, pkg/service/service.go
Because
- The `checkConnector()` use wrong `owner_id`
This commit
- Fix `checkConnector()` to use right `owner_id`
=> chore: fix CheckConnectorByUID bug

cmd/init/main.go, go.mod, go.sum
Because
- it take too long to download all Airbyte images
This commit
- only pre-download Airbyte image if the image is needed
=> chore: only preDownloadImage if the image is needed

integration-test/grpc-destination-connector-private.js, integration-test/grpc-destination-connector-public-with-jwt.js, integration-test/grpc-destination-connector-public.js, integration-test/rest-destination-connector-public-with-jwt.js, integration-test/rest-destination-connector-public.js, integration-test/rest-destination-connector.js, integration-test/rest-source-connector-public.js, pkg/handler/publicHandler.go, pkg/service/service.go
Because
- The setting of connector may be complex, so we must let use has the ability to save the unfinished connector
This commit
- When create connector, the desired state will be disconnected
- If the connector desired state is connected, then you can not update the connector
- The only exception is `[source|destination]-[grpc|http]`. They will always be connected.
=> chore: allow unfinished connector configuration

go.mod, go.sum, pkg/connector/connector.go, pkg/handler/publicHandler.go
Because
- We don't want to return credential data in api response
This commit
- Add credential masking functions. Currently, we use a fixed string to represent the masked data as a temporary solution.
=> chore: implement credential masking function

cmd/migration/main.go, cmd/migration/migration000003.go
Because
- need to migrate the existing model resources to the new model-connector
This commit
- add migration scripts for model-connectors
=> chore: add migration scripts for model-connectors

.github/workflows/integration-test.yml, Makefile, integration-test/const.js
Because
- Some of our test-cases may be cross projects, we need to use different apigateway endpoints
This commit
- update integration test params
=> chore: update integration test params

Makefile, cmd/init/main.go, cmd/init/prebuilt_list.json, config/config.go, config/config.yaml, pkg/handler/publicHandler.go
Because
- add pre-built connectors scripts for public connectors
This commit
- add pre-built connectors scripts
- add constraint that user can not create connector id start with `instill-`
=> chore: add pre-built connectors scripts

go.mod, go.sum, pkg/handler/publicHandler.go, pkg/service/service.go
Because
- The connectConnector behavior is not explicit. When it return `connected`, it may not actually connected.
This commit
- Improve connectConnector mechanism
=> chore: improve connectConnector mechanism

cmd/migration/main.go, config/config.yaml, go.mod, go.sum, integration-test/const.js, integration-test/grpc-destination-connector-private.js, integration-test/grpc-destination-connector-public-with-jwt.js, integration-test/grpc-destination-connector-public.js, integration-test/grpc-source-connector-private.js, integration-test/grpc-source-connector-public-with-jwt.js, integration-test/grpc-source-connector-public.js, integration-test/rest-destination-connector-public-with-jwt.js, integration-test/rest-destination-connector-public.js, integration-test/rest-destination-connector.js, integration-test/rest-source-connector-private.js, integration-test/rest-source-connector-public-with-jwt.js, integration-test/rest-source-connector-public.js, pkg/constant/constant.go, pkg/db/migration/000004_init.up.sql, pkg/handler/privateHandler.go, pkg/service/service.go
Because
- it is not user friendly to have separated `http` and `grpc` connector
This commit
- refactor `source-http|grpc` to `trigger` and `destination-http|grpc` to `response`
=> chore: refactor `source-http|grpc` to `trigger` and `destination-http|grpc` to `response`

go.mod, go.sum, pkg/service/service.go
Because
- memory leak happened in connector-ai and blockchain
This commit
-  update connector-ai/blockchain pkg to fix memory leak
=> chore: update connector-ai/blockchain pkg to fix memory leak

go.mod, go.sum, pkg/handler/privateHandler.go, pkg/handler/publicHandler.go, pkg/handler/utils.go, pkg/service/convert.go, pkg/service/service.go
Because
- we need a new view mode to return `configuration` but not return `connector_definition`
This commit
- add `VIEW_CONFIGURATION`
=> chore: add VIEW_CONFIGURATION

cmd/init/main.go, go.mod, go.sum, pkg/handler/privateHandler.go, pkg/handler/publicHandler.go, pkg/repository/repository.go, pkg/service/convert.go, pkg/service/service.go
Because
- we need to return soft-deleted connector-resources when needed
This commit
- support param `show_deleted` to return soft-deleted connector-resources
=> chore: support param `show_deleted` to return soft-deleted connector-resources

pkg/utils/utils.go
Because
- fix wrong connector uid assignment
This commit
- fix wrong connector uid assignment
=> chore(metric): fix wrong uid assignment

cmd/main/main.go, pkg/constant/constant.go
Because
- the default grpc message size limit is only 4MB, which is not enough
This commit
- increase grpc message size limit to 32MB
=> chore: increase grpc message size limit

go.mod, go.sum, pkg/handler/privateHandler.go, pkg/handler/publicHandler.go, pkg/usage/usage.go
Because
- the grpc-gateway will convert `int64` to `string`
This commit
- use `int32` for `page_size` and `total_size` to avoid this problem
=> fix(proto,handler): use `int32` in proto pkg to prevent the `total_size` converted to `string`

cmd/main/main.go, pkg/constant/constant.go, pkg/service/service.go
Because
- the `user_id` injection in backend is unsafe
- we are going to change the default_user_id to `admin`
This commit
- remove `user_id` injection
- change the default_user_id to `admin`
=> chore(service): remove unsafe user_id injection and update default_user_id

.github/CONTRIBUTING.md, .github/labeler.yml, README.md
Because
- we'd like to keep `README.md` succinct and put contributing guidelines in the repo `.github/CONTRIBUTING.md`
This commit
- move the content of local development into the repo contributing guideline.
- update Github label
=> docs(contributing): update contributing guidelines and labeler

cmd/main/main.go
Because
- Currently backends in Instill Base Instill VDP and Instill Model will emit a huge amount of logs with level Info, which can overwhelm stdout
This commit
- Refactor grpc logger `verbosity` and bypass successful private function calls
=> refactor(logging): reduce unnecessary log emission

pkg/handler/publicHandler.go, pkg/service/service.go, pkg/utils/utils.go
Because
- the connector resource field can not be reset with empty value, but we should allow it
This commit
- fix bug
=> fix(handler): fix connector resource field can not be reset with empty value
